apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.mariadb.name }}
  labels:
    app: {{ .Values.deployment.mariadb.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.mariadb.app }}
  template:
    metadata:
      name: {{ .Values.deployment.mariadb.app }}
      labels:
        app: {{ .Values.deployment.mariadb.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.mariadb.app }}
          image: {{ .Values.deployment.mariadb.image }}:{{ .Values.deployment.mariadb.tags }}
          ports:
            - containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.mariadb.secret }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-storage
      volumes:
        - name: mariadb-storage
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.fastapi.name }}
  labels:
    app: {{ .Values.deployment.fastapi.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.fastapi.app }}
  template:
    metadata:
      name: {{ .Values.deployment.fastapi.app }}
      labels:
        app: {{ .Values.deployment.fastapi.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.fastapi.app }}
          image: {{ .Values.deployment.fastapi.image }}:{{ .Values.deployment.fastapi.tags }}
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.nginx.name }}
  labels:
    app: {{ .Values.deployment.nginx.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.nginx.app }}
  template:
    metadata:
      name: {{ .Values.deployment.nginx.app }}
      labels:
        app: {{ .Values.deployment.nginx.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.nginx.app }}
          image: {{ .Values.deployment.nginx.image }}:{{ .Values.deployment.nginx.tags }}
          ports:
            - containerPort: 80
              protocol: TCP
