apiVersion: v1
kind: Service
metadata:
  name: k8s-mariadb-svc    # 주의! 이름 변경하면 안됌. 고정되어있음
spec:
  selector:
    app: {{ .Values.service.fastapi.app }}
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-fastapi-svc       # 주의! 이름 변경하면 안됌. 고정되어있음
spec:
  selector:
    app: {{ .Values.service.fastapi.app }}
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nginx.name }}
spec:
  selector:
    app: {{ .Values.service.nginx.app }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

